name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v5.0.0
      with:
        cmd: install

    - name: Run tests
      run: yarn test

