name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.0, 20]  # Specify both Node.js versions

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Ensure this is using v4

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Ensure this is using v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v5.0.0
      with:
        cmd: install

    - name: Run tests
      run: yarn test

